# Generated by Django 5.2.7 on 2025-11-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_college_logo_alter_department_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_colleges', to=settings.AUTH_USER_MODEL),
        ),
    ]
