# Generated by Django 5.2.7 on 2025-11-28 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_college_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_colleges', to=settings.AUTH_USER_MODEL),
        ),
    ]
