# Generated by Django 5.2.7 on 2025-12-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_college_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerships',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email of contact person.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='partnerships',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Name of the contact person for this partnership.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerships',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone number for the contact person.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partnerships',
            name='date_ended',
            field=models.DateField(blank=True, help_text='End date (leave blank if ongoing).', null=True),
        ),
        migrations.AddField(
            model_name='partnerships',
            name='date_started',
            field=models.DateField(blank=True, help_text='When the partnership began.', null=True),
        ),
    ]
