# Generated by Django 5.2.7 on 2025-12-05 20:22

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_partnerships_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/default_logo.png', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='college_logos/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/default_logo.png', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='department_logos/'),
        ),
        migrations.AlterField(
            model_name='partnerships',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/default_logo.png', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='partnership_logos/'),
        ),
    ]
