# Generated by Django 5.2.7 on 2025-12-05 21:34

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_college_logo_alter_department_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, default='college_logos/default_logo.png', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='college_logos/'),
        ),
    ]
