# Generated by Django 5.2.7 on 2025-12-05 21:38

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_college_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dwqimnugx/image/upload/v1764968131/default_logo_fhrtcn.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='college_logos/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dwqimnugx/image/upload/v1764968131/default_logo_fhrtcn.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='department_logos/'),
        ),
        migrations.AlterField(
            model_name='partnerships',
            name='logo',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dwqimnugx/image/upload/v1764968131/default_logo_fhrtcn.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='partnership_logos/'),
        ),
    ]
