# Generated by Django 5.2.7 on 2025-12-05 21:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_college_logo_alter_department_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, default='default_logo_fhrtcn.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='college_logos/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, default='default_logo_fhrtcn.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='department_logos/'),
        ),
        migrations.AlterField(
            model_name='partnerships',
            name='logo',
            field=models.ImageField(blank=True, default='default_logo_fhrtcn.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='partnership_logos/'),
        ),
    ]
