# Generated by Django 5.2.7 on 2025-12-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_college_logo_alter_department_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, default='college_logos/default_logo_fhrtcn.png', null=True, upload_to='college_logos/'),
        ),
    ]
