# Generated by Django 5.2.7 on 2025-12-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_college_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='college_logos/'),
        ),
    ]
